version: '3'

services:
  db:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: websockets_model_updates
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: project.settings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    expose:
    - "6379"
